AWSTemplateFormatVersion: 2010-09-09
Description: |
  Cloudformation Template for kittens carousel static website deploy on s3 through
  cloudfront and route 53
Parameters:
  HostedZoneName:
    Description: DNS Name of existing Amazon Route 53 hosted zone. exp. emrebaykal.click
    Type: AWS::Route53::HostedZone::Id
  KittensSubDomainName:
    Description: Full domain name for the App. ex. kittens.emrebaykal.click
    Type: String
    AllowedPattern: (?!-)[a-zA-Z0-9-.]{1,63}(?<!-)

Resources:
  MyBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref KittensSubDomainName
      OwnershipControls:
        Rules:
          - ObjectOwnership: ObjectWriter
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
      WebsiteConfiguration:
        IndexDocument: "index.html"
        
  KittensBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref MyBucket
      PolicyDocument:
        Statement:
          - Action: s3:GetObject
            Effect: Allow
            Principal: '*'
            Sid: PublicReadGetObject
            Resource: !Join ['', ['arn:aws:s3:::', !Ref 'MyBucket', /*]]

  MyCloudfront:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - !Ref KittensSubDomainName
        Comment: Cloudfront Distribution pointing to Kittens S3 Bucket
        DefaultCacheBehavior:
          AllowedMethods:
           - GET 
           - HEAD
          ForwardedValues:
            QueryString: true
          Compress: true   
          TargetOriginId: KittensOrigin
          ViewerProtocolPolicy: allow-all
        DefaultRootObject: index.html
        Enabled: true
        HttpVersion: http2 
        Origins:
          - DomainName: !Select [2, !Split ["/", !GetAtt MyBucket.WebsiteURL]] 
            Id: KittensOrigin
            CustomOriginConfig:
              OriginProtocolPolicy: http-only
        PriceClass: PriceClass_All
        ViewerCertificate: 
         AcmCertificateArn: arn:aws:acm:us-east-1:374821970250:certificate/846bcb10-765e-4e67-af56-b7973176e32c
         SslSupportMethod: sni-only

  MyRecordName:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId: !Ref HostedZoneName
      RecordSets:
      - Name: !Ref KittensSubDomainName
        Type: A
        AliasTarget:
          DNSName: !GetAtt  MyCloudfront.DomainName
          HostedZoneId: Z2FDTNDATAQYW2


Outputs:
  BucketName:
    Description: S3 Bucket URL for Kittens Website
    Value: !GetAtt MyBucket.WebsiteURL
  CloudfrontEndpoint:
    Description: Endpoint for Kittens Cloudfront
    Value: !GetAtt MyCloudfront.DomainName
  FullDomainName:
    Description: Full Domain Name of my Application
    Value: !Ref KittensSubDomainName